### ISSUE TITLE
User Story 1: Søge flyafgange enkelt selskab

### ISSUE THREAD

**Issue by mathiasj64** [mathiasj64/Momondo#1]

**Comment by PhilipWestChristiansen** [comment]
Som bruger kan jeg se om der flyver flyvere

**Comment by Phirt** [comment]
USPIK

**Comment by PhilipWestChristiansen** [comment]
Task 1:

Lav HTML side med søgefunktion som tager udgangspunkt i vores prototype.

**Comment by Phirt** [comment]
Task 2:

Lav en Javascript side med angular, som kalder på en url via en HTTP get metode.
